### ISSUE TITLE
Uninstall Settings Directory Registry Key

### ISSUE THREAD

**Issue by papeh** [sillsdev/genericinstaller#7]
Install an app using the Generic Installer, then uninstall it using the Add or Remove Programs control panel.
Expected: the registry contains no residue.
Actual: the registry still contains the Settings_Directory string under the app's key.

**Comment by papeh** [comment]
Framework.wxs contains the following: `<Component Id='RegKeySettingsDir' Guid='*' Permanent='yes'>`. So it looks like we are intentionally leaving this key following uninstall. My first guess is that we want to find the user's old projects if the app is uninstalled and reinstalled. @GlennPruitt, is this correct?

**Comment by GlennPruitt** [comment]
Yes, that is the intention.  It is purely a Paratext requirement.
